import type { Strings } from "./strings.id";

/** English UI copy — opt-in locale, shape-checked against `strings.id.ts`. */
export const en: Strings = {
  appName: "Patungan",
  nav: {
    landing: "Home",
    seasons: "Seasons",
    results: "Results",
    dashboard: "Dashboard",
    account: "Account",
    operator: "Operator",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    mainMenu: "Main menu",
  },
  landing: {
    heroTags: ["Payment & Consumer App", "PMI/TKI diaspora", "Quadratic matching"],
    heroLede:
      "Rp50k from many perantau isn't just a donation. On Patungan, every contribution becomes a public signal that pulls the sponsor pool toward the most-backed village projects.",
    heroPoolLabel: "Matching pool",
    heroDonorLabel: "Backers",
    heroStatusLabel: "Status",
    waitingPool: "Waiting",
    primaryCta: "Browse projects",
    secondaryCta: "See results",
    liveProjectBadge: "Live project",
    waitingProjectTitle: "Waiting for project data",
    heroTopLine: (n: number) => `${n} backers pulling the largest match.`,
    heroTopLineEmpty: "Connect a deployment to see live data.",
    matchEngineLabel: "Match engine",
    matchEngineTitle: "Soroban finalization",
    crowdShareLabel: "Top share",
    ofPoolSuffix: "of matching pool",
    proofTag: "Soroban proof layer",
    proofBody:
      "The blockchain isn't a sticker: the contract witnesses contributions, the registry limits sybils, and payouts come from auditable math.",
    proofComment: "one matching season, end to end",
    proofSteps: [
      {
        title: "Pool escrow",
        copy: "Sponsors deposit into the contract, not a committee's bank account.",
      },
      {
        title: "One ID, one voice",
        copy: "The verified registry limits sybils: one identity, one voice.",
      },
      {
        title: "Tagged donations",
        copy: "Every chip-in is recorded with donor, project_id, amount, and ledger.",
      },
      {
        title: "Quadratic allocation",
        copy: "The contract computes (Σ√c)² per campaign and splits the matching pool — headcount wins, not one whale.",
      },
    ],
    directoryComment: "public directory — every campaign curator-verified",
    seasonRef: (id: string | number) => `season #${id}`,
    title: "Patungan",
    subtitle: "Chip in together, matched fairly.",
    poolLabel: "Matching pool",
    sponsorLabel: "Sponsored by",
    sponsorName: "Pemprov Jawa Timur",
    statusOpen: "Open",
    statusFinalized: "Finalized",
    roundEndLabel: "Ends",
    notInitialized: "Round not open yet",
    waitingSponsor: "Waiting for sponsor",
    donorCountSuffix: "backers",
    projectedMatchLabel: "Projected match",
    finalMatchLabel: "Final match",
    noMatchYet: "—",
  },
  categories: {
    DevelopingRegions: "Developing Regions",
    DisasterRelief: "Disaster Relief",
    EducationHealth: "Education & Health",
  } as Record<string, string>,
  discovery: {
    heading: "Explore campaigns",
    tagline: "Small support from many people, matched fairly.",
    searchPlaceholder: "Search campaigns…",
    sortLabel: "Sort",
    sort: {
      mostBacked: "Most backed",
      newest: "Newest",
      closingSoon: "Closing soon",
    },
    allFilter: "All",
    createCta: "Submit a campaign",
    resultCount: (n: number) => `${n} campaigns`,
    emptyApproved: "No approved campaigns yet.",
    emptyFiltered: "No campaigns match this filter.",
    resetFilters: "Reset filters",
    // Season / round banner
    season: "Matching Season",
    live: "Live",
    scopeAll: "All categories",
    scopeLabel: "Categories this season",
    endsInLabel: "Ends in",
    endedLabel: "Season ended",
    noRound: "No active matching season",
    noRoundHint: "Direct donations stay open. The next season is coming soon.",
    countdown: { day: "d", hour: "h", min: "m", ended: "Ended" },
    // Card
    donorSuffix: "backers",
    donorLabel: "Backers",
    directShort: "Direct",
    projectedShort: "Projected",
    totalShort: "Total",
    matchSuffix: "match",
    noThumbAlt: "No image",
    // Onboarding "how it works" strip — QF explainer for cold visitors
    howItWorks: {
      overline: "How it works",
      steps: [
        {
          n: "01",
          title: "Donate directly, anytime",
          body: "Pick a campaign you trust, then donate directly — no need to wait for a season.",
        },
        {
          n: "02",
          title: "Number of people, not size of gift",
          body: "Many small donors send a stronger signal than one big donor.",
        },
        {
          n: "03",
          title: "Matching funds split every season",
          body: "At the end of each season, sponsor funds are split following that signal, quadratically.",
        },
      ],
      viz: {
        crowd: "many small donors",
        whale: "one big donor",
        beats: "beats",
        sr: "Many small donors beat one big donor.",
      },
    },
  },
  campaign: {
    back: "Back to explore",
    notFoundTitle: "Campaign not found",
    notFoundBody: "This campaign may not exist yet, or the link is wrong.",
    backHome: "Back to home",
    byOwner: "Run by",
    storyHeading: "About this campaign",
    raisedLabel: "Total direct donations",
    thisRoundHeading: "This matching season",
    donorSuffix: "backers",
    projectedMatchLabel: "Projected quadratic match",
    notInRound:
      "Not part of an active matching season yet — direct donations still count toward the next season's match.",
    status: {
      Pending: "This campaign is still awaiting curation. Donations open once a curator approves it.",
      Rejected: "This campaign didn't pass curation and can't receive donations.",
      Cancelled: "This campaign has been cancelled.",
    } as Record<string, string>,
    create: {
      back: "Back to explore",
      heading: "Submit a campaign",
      subtitle:
        "Tell your campaign's story, upload one image, then submit for curation. Once a curator approves it, your campaign goes public and can receive donations.",
      // Gate ladder (mirrors the contribute gate)
      connectPrompt: "Connect a Testnet wallet to submit a campaign.",
      wrongNetwork: "Switch Freighter to Testnet to continue.",
      tierGateTitle: "Verify first",
      tierGateBody: "You need Basic-tier verification to submit a campaign.",
      tierGateCta: "Verify now",
      // Fields
      titleLabel: "Campaign title",
      titlePlaceholder: "e.g. Clean water well for Dusun Sumber",
      categoryLabel: "Category",
      storyLabel: "Campaign story",
      storyPlaceholder:
        "Explain who's helped, what's being funded, and why it matters.",
      payoutLabel: "Payout address",
      payoutHelper: "Default: your wallet. Funds raised are disbursed to this address.",
      payoutReset: "Use my wallet",
      imageLabel: "Campaign image",
      // Image dropzone
      image: {
        dropPrompt: "Drag an image here or choose a file",
        dropHint: "PNG or JPG, pinned to IPFS",
        pickFile: "Choose file",
        uploading: "Uploading image…",
        replace: "Replace image",
        remove: "Remove",
        cidLabel: "CID",
        errorFallback: "Failed to pin image. Try again.",
        previewAlt: "Campaign image preview",
      },
      // Client-side validation
      invalid: {
        titleRequired: "Title is required.",
        titleTooLong: "Title is 96 characters max.",
        storyRequired: "Story is required.",
        storyTooLong: "Story is 1024 characters max.",
        payoutInvalid: "Invalid Stellar address (must start with G, 56 characters).",
        imageRequired: "Upload one campaign image.",
      } as Record<string, string>,
      // Submit tx
      submit: "Submit for curation",
      awaiting: "Open Freighter to sign…",
      submitting: "Sending transaction…",
      // Success
      successTitle: "Campaign submitted — awaiting curation",
      successBody:
        "Your campaign is recorded on-chain with status Pending curation. Once a curator approves it, it goes public and can receive donations.",
      viewCampaign: "View campaign",
      createAnother: "Submit another campaign",
    },
    jejak: {
      tag: "On-chain trail",
      heading: "Where your Rp50k goes",
      steps: [
        "Your donation is recorded in the contract with address, amount, and ledger.",
        "Your contribution raises this campaign's (Σ√c)² weight — a public signal, not a promise.",
        "At season's end, the matching pool is split along that signal. Anyone can audit it.",
      ],
      artifactsLabel: (id: number) => `Campaign artifacts #${id}`,
      categoryLabel: "category",
    },
    ledger: {
      heading: "Backer ledger",
      body: "Every chip-in to this campaign, straight from the contract's event log.",
      empty: "No donations inside the RPC retention window yet.",
      retention: "Only donations within the Testnet RPC retention window are shown.",
    },
    contribute: {
      cta: "Chip in",
      amountLabel: "Choose amount",
      customChip: "Custom amount",
      customPlaceholder: "e.g. 25000",
      customInvalid: "Enter a positive whole number.",
      confirm: "Send & sign",
      awaiting: "Open Freighter to sign…",
      submitting: "Sending transaction…",
      successTitle: "Thanks — your contribution is on-chain.",
      done: "Done",
      cancel: "Cancel",
      connectPrompt: "Connect a Testnet wallet to chip in.",
      wrongNetwork: "Switch Freighter to Testnet to continue.",
      tierGateTitle: "Verify first",
      tierGateBody: "You need Basic-tier verification to chip in.",
      tierGateCta: "Verify now",
    },
  },
  project: {
    backToLanding: "Back to home",
    notFound: "Project not found.",
    raisedLabel: "Raised",
    contributeCta: "Chip in",
    roundClosedCta: "Round closed",
    stories: {
      0: "SDN 2 Elementary School's roof leaks every rainy season. This fund replaces the tin roof so kids can study safe and dry.",
      1: "RW 5's community garden supplies fresh vegetables to the local health post. This fund buys seeds and basic farming tools.",
      2: "Dusun Sumber residents walk far every day for clean water. This fund pays for a drilled well for the community.",
    } as Record<number, string>,
  },
  contribute: {
    title: "Contribute to",
    amountLabel: "Choose amount",
    connectFirst: "Connect a Testnet wallet to continue.",
    confirmCta: "Send & sign",
    awaitingSignature: "Open Freighter to sign…",
    submitting: "Sending transaction…",
    successTitle: "Contribution successful!",
    viewOnExplorer: "View transaction on Explorer",
    close: "Close",
    cancel: "Cancel",
    errors: {
      NotVerified: "This address isn't verified yet.",
      RoundClosed: "This season is closed to new contributions.",
      UnknownProject: "Project not found.",
      InvalidAmount: "Invalid amount.",
      rejected: "Signature cancelled.",
      generic: "Transaction failed. Try again.",
    } as Record<string, string>,
  },
  seasons: {
    title: "Season archive",
    subtitle:
      "Every matching season ever opened, newest first. Finished seasons show the campaigns with the biggest match.",
    seasonLabel: (id: number) => `Season #${id}`,
    poolLabel: "Matching pool",
    sponsorLabel: "Sponsor",
    scopeLabel: "Categories",
    scopeAll: "All categories",
    status: {
      Open: "Live",
      Finalized: "Finished",
      Cancelled: "Cancelled",
    } as Record<string, string>,
    liveEndsIn: "Ends in",
    liveEnded: "Awaiting finalization",
    liveProjection: "Live matching projection",
    countdown: { day: "d", hour: "h", min: "m", ended: "Ended" },
    topHeading: "Biggest match",
    noMatches: "No campaigns matched this season.",
    cancelledNote: "This season was cancelled before finalization. Funds were returned to the sponsor.",
    viewResults: "View results",
    empty: "No matching seasons yet.",
    emptyHint: "The first season will show up here once a sponsor opens a round.",
  },
  results: {
    title: "Matching results",
    seasonLabel: (id: number) => `Season #${id}`,
    notFinalized: "This season isn't finalized yet. Here's the projected match based on current contributions.",
    finalized: "Final results for this season.",
    roundPickerLabel: "Season",
    directLabel: "Direct",
    matchedLabel: "Matched",
    donorSuffix: "backers",
    poolLabel: "Matching pool",
    totalMatchedLabel: "Total matching funds distributed",
    verdict: "Matching funds follow the number of backers, not the size of the gift.",
    empty: "No contributions to match this season yet.",
    emptyHint: "Results will show up once campaigns receive donations this season.",
    notFoundTitle: "Season not found",
    notFoundBody: "This season may not exist yet, or the link is wrong.",
    backToSeasons: "View season archive",
    noRounds: "No matching seasons yet.",
    barLabel: "Comparison of direct donations and matching funds",
    slowLoad: "On-chain data is taking longer than usual.",
  },
  operator: {
    title: "Operator Console",
    subtitle:
      "Run one full matching season: open the round, fund the pool, curate campaigns, then finalize.",
    connectPrompt: "Connect an operator wallet to access this console.",
    notRole:
      "The connected wallet doesn't hold an operator role (admin, curator, or verifier).",
    wrongNetwork: "Switch Freighter to Testnet to continue.",
    awaiting: "Open Freighter to sign…",
    submitting: "Sending transaction…",
    status: {
      connectedAs: "Connected as",
      roles: "Roles",
      roleAdmin: "Admin",
      roleCurator: "Curator",
      roleAttester: "Verifier",
      liveRound: "Live season",
      noRound: "No open season",
      poolLabel: "Matching pool",
      scopeAll: "All categories",
      endsLabel: "Ends",
      ended: "Ended",
    },
    lifecycleHeading: "Matching season",
    governanceHeading: "Governance",
    step: { open: "01 · Open season", fund: "02 · Fund pool", finalize: "03 · Finalize" },
    open: {
      heading: "Open a matching season",
      description:
        "Start a new season: set an end date and which categories are matched. Only one season can be open at a time.",
      endLabel: "End date",
      endHelper: "Shown to donors as a countdown.",
      categoriesLabel: "Categories this season",
      categoriesHint: "Leave empty to match every category.",
      cta: "Open season",
      successTitle: "Season opened!",
      alreadyOpen: (id: number) => `Season #${id} is already running. Finalize it before opening a new one.`,
      invalidDate: "Pick an end date in the future.",
    },
    fund: {
      heading: "Fund the matching pool",
      description:
        "Deposit matching funds for the season currently running. Requires Institution-tier verification.",
      amountLabel: "Fund amount (IDR)",
      echoLabel: "Will deposit",
      cta: "Send funds",
      successTitle: "Matching funds sent!",
      invalidAmount: "Enter a positive whole number.",
      needsRound: "Open a season first before funding it.",
      tierGateTitle: "Institution tier required",
      tierGateBody:
        "Only Institution-verified wallets can fund the matching pool. Use the verification console below to raise this wallet's tier.",
    },
    finalize: {
      heading: "Finalize the season",
      description:
        "Closes the season to new contributions and computes the quadratic match. Cannot be undone.",
      cta: "Finalize season",
      confirmMessage: "Finalizing can't be undone. Continue?",
      confirmCta: "Yes, finalize now",
      cancelCta: "Cancel",
      successTitle: "Season finalized!",
      viewResults: "View results",
      needsRound: "No open season to finalize.",
    },
    curation: {
      heading: "Curation queue",
      description: "New campaigns await approval before they go public and can receive donations.",
      empty: "No campaigns awaiting curation.",
      pendingBadge: "Pending",
      approve: "Approve",
      reject: "Reject",
      approving: "Approving…",
      rejecting: "Rejecting…",
      byOwner: "By",
      approvedToast: "Campaign approved.",
      rejectedToast: "Campaign rejected.",
    },
    verify: {
      heading: "Manual verification",
      description:
        "Set a verification tier for an address — the testnet stand-in path for a KYC anchor.",
      addressLabel: "Wallet address (G…)",
      tierLabel: "Tier",
      tiers: { None: "None", Basic: "Basic", Institution: "Institution" } as Record<string, string>,
      cta: "Set tier",
      successTitle: "Verification tier set!",
      invalidAddress: "Invalid Stellar address (must start with G, 56 characters).",
    },
    viewOnExplorer: "View transaction on Explorer",
    errors: {
      RoundAlreadyOpen: "A season is already running.",
      RoundNotOpen: "This season is no longer open for this action.",
      AlreadyFinalized: "This season has already been finalized.",
      NothingToMatch: "No contributions to match yet.",
      TierTooLow: "Verification tier isn't high enough (Institution required).",
      NotAdmin: "Only an admin can do this.",
      NotCurator: "Only a curator can do this.",
      NotAttester: "Only a verifier can do this.",
      ProjectNotPending: "This campaign isn't awaiting curation.",
      InvalidAmount: "Invalid amount.",
      rejected: "Signature cancelled.",
      generic: "Transaction failed. Try again.",
    } as Record<string, string>,
  },
  dashboard: {
    title: "My dashboard",
    subtitle:
      "Campaigns you've submitted, total donations raised, and each season's matching payout.",
    createCta: "Submit a campaign",
    connectPrompt: "Connect a Testnet wallet to see your campaigns.",
    wrongNetwork: "Switch Freighter to Testnet to continue.",
    empty: "You don't have any campaigns yet.",
    emptyHint: "Submit your first campaign to start receiving donations and matching funds.",
    statusPill: {
      Pending: "Awaiting curation",
      Approved: "Active",
      Rejected: "Rejected",
      Cancelled: "Cancelled",
    } as Record<string, string>,
    lifetimeLabel: "Total direct donations",
    seasonsHeading: "Payouts by season",
    seasonsLoading: "Loading payouts…",
    noSeasons: "This campaign hasn't been part of a finalized matching season yet.",
    round: {
      label: (id: number) => `Season #${id}`,
      directLabel: "Direct",
      donorSuffix: "backers",
      matchedLabel: "Matched",
      claim: "Claim matching funds",
      claiming: "Claiming…",
      claimed: "Already claimed",
      nothing: "No match this season",
    },
    direct: {
      heading: "Donations outside a season",
      body: "Donations that came in while no season was active — can be claimed anytime.",
      claim: "Claim direct donations",
      claiming: "Claiming…",
      claimed: "Direct donations have been disbursed.",
    },
    awaiting: "Open Freighter to sign…",
    submitting: "Sending transaction…",
    claimedTitle: "Funds claimed successfully!",
    viewOnExplorer: "View transaction on Explorer",
  },
  account: {
    title: "My contributions",
    subtitle:
      "Your direct donation history, reconstructed from on-chain records — grouped by campaign.",
    connectPrompt: "Connect a Testnet wallet to see your contribution history.",
    wrongNetwork: "Switch Freighter to Testnet to continue.",
    tierLabel: "Verification",
    tier: { None: "Not verified", Basic: "Basic", Institution: "Institution" } as Record<
      string,
      string
    >,
    impactLabel: "My total impact",
    campaignCount: (n: number) => `${n} campaigns`,
    giftCount: (n: number) => `${n} donations`,
    myTotalLabel: "My donations",
    unknownCampaign: (id: number) => `Campaign #${id}`,
    viewCampaign: "View campaign",
    viewTx: "View on Explorer",
    empty: "You haven't donated yet.",
    emptyHint:
      "Your first donation will show up here, recorded straight from the on-chain transaction.",
    exploreCta: "Explore campaigns",
    retentionNote:
      "Only donations within the Testnet RPC retention window can be shown.",
  },
  tierBadge: {
    currentLabel: "Your verification tier",
    tiers: {
      None: "Not verified",
      Basic: "Basic verified",
      Institution: "Institution verified",
    } as Record<string, string>,
    unlocks: {
      None: "Verify to start contributing and submitting campaigns.",
      Basic: "You can contribute and submit campaigns.",
      Institution: "You can contribute, submit campaigns, and fund the matching pool.",
    } as Record<string, string>,
  },
  verify: {
    title: "Verification",
    subtitle:
      "Verify once to unlock contributing and campaign submission. Your identity data is never stored here — only your verification tier is recorded on-chain.",
    connectPrompt: "Connect a Testnet wallet to start verification.",
    wrongNetwork: "Switch Freighter to Testnet to continue.",
    ladderHeading: "What each tier unlocks",
    ladder: [
      { tier: "Basic", unlock: "Contribute & submit campaigns" },
      { tier: "Institution", unlock: "Fund the matching pool as a sponsor" },
    ],
    sep10: {
      overline: "01 · Proof of ownership",
      heading: "Prove you own this wallet",
      description:
        "Sign the anchor's challenge (SEP-10) to prove wallet ownership. No funds move.",
      cta: "Start proof of ownership",
      pending: "Contacting anchor…",
      awaiting: "Open Freighter to sign…",
      successTitle: "Ownership proven",
      successBody: "The anchor issued a session token. Continue to tier assignment.",
      notConfiguredTitle: "Anchor not configured",
      notConfiguredBody:
        "No SEP-10 anchor is connected in this environment yet. You can still use the simulated testnet tier-assignment path below.",
      errors: {
        "not-configured": "No anchor is configured in this environment.",
        toml: "The anchor's SEP-10 endpoint wasn't found.",
        challenge: "The anchor rejected the verification request. Try again.",
        "invalid-challenge": "The anchor's challenge is invalid.",
        signature: "Signature cancelled.",
        token: "The anchor rejected the signature. Try again.",
        network: "Couldn't reach the anchor. Check your connection and try again.",
        generic: "Anchor verification failed. Try again.",
      } as Record<string, string>,
    },
    kyc: {
      overline: "01b · KYC details",
      heading: "Send KYC details to the anchor",
      description:
        "This anchor publishes a KYC service (SEP-12). Fill in a few details for the anchor to review.",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      cta: "Send to anchor",
      submitting: "Sending to anchor…",
      polling: "Checking status with anchor…",
      status: {
        NEEDS_INFO: "The anchor needs more information.",
        PROCESSING: "The anchor is processing your submission.",
        PENDING: "Waiting on the anchor's decision.",
        ACCEPTED: "The anchor accepted your KYC. Continue to tier assignment.",
        REJECTED: "The anchor rejected this KYC submission.",
      } as Record<string, string>,
      errors: {
        "not-configured": "No anchor is configured in this environment.",
        "kyc-not-configured":
          "This anchor doesn't publish a KYC service (SEP-12) — continue via the simulated testnet tier-assignment path below.",
        "kyc-rejected": "The anchor rejected the KYC submission. Try again.",
        network: "Couldn't reach the anchor. Check your connection and try again.",
        generic: "KYC submission failed. Try again.",
      } as Record<string, string>,
    },
    attest: {
      overline: "02 · Tier assignment",
      heading: "Get your verification tier",
      simBadge: "Testnet simulation",
      realBadge: "Anchor KYC accepted",
      description:
        "In production, the anchor approves KYC and then writes your tier. On testnet, the operator (holding the verifier role) stands in for the anchor.",
      attesterHint:
        "This wallet holds the verifier role — you can set a tier directly as the anchor stand-in.",
      tierLabel: "Tier",
      tiers: { Basic: "Basic", Institution: "Institution" } as Record<string, string>,
      cta: "Approve (simulated KYC)",
      successTitle: "Verification tier set!",
      fallbackTitle: "Waiting on the operator's tier assignment",
      fallbackBody:
        "On testnet, tier assignment is handled by the operator in place of the anchor. Your wallet ownership is already proven — ask the operator to set your tier via the console.",
      fallbackCta: "Open operator console",
      alreadyTitle: "You're already verified",
      alreadyBody: "Nothing else to do. You're ready to contribute.",
      exploreCta: "Explore campaigns",
    },
    submitting: "Sending transaction…",
    viewOnExplorer: "View transaction on Explorer",
    tierError: "Failed to load verification tier. Try again.",
  },
  wallet: {
    connect: "Connect Wallet",
    connecting: "Connecting…",
    disconnect: "Disconnect Wallet",
    notInstalled: "Install Freighter",
    wrongNetworkPill: "Wrong network",
    testnetPill: "Testnet",
    wrongNetworkBanner:
      "Freighter isn't connected to Testnet. Switch networks in Freighter to continue.",
    connectFailed: "Failed to connect wallet. Try again.",
  },
  explorer: {
    viewTx: "View transaction on Explorer",
    viewContract: "View contract on Explorer",
  },
  footer: {
    transparency: "Every action is recorded on-chain on Stellar Testnet.",
  },
  notFound: {
    title: "Page not found",
    body: "This route isn't in the ledger. Check the link, or head back home.",
    cta: "Back to home",
  },
  loading: "Loading…",
  empty: "No projects yet",
  errorGeneric: "Something went wrong. Try again.",
  retry: "Retry",
  staleData: "Couldn't load updates — showing the last known data.",
  errors: {
    AlreadyInitialized: "The contract is already initialized.",
    NotAdmin: "Only an admin can do this.",
    NotVerified: "This address isn't verified yet.",
    RoundClosed: "This season is closed to new contributions.",
    RoundNotOpen: "This season is no longer open for this action.",
    AlreadyFinalized: "This season has already been finalized.",
    NotFinalized: "This season isn't finalized yet.",
    UnknownProject: "Campaign not found.",
    DuplicateProject: "This campaign is already registered.",
    AlreadyDisbursed: "This campaign's funds have already been disbursed.",
    InvalidAmount: "Invalid amount.",
    NothingToMatch: "No contributions to match yet.",
    NotCurator: "Only a curator can do this.",
    ProjectNotApproved: "This campaign hasn't been approved by a curator yet.",
    ProjectNotPending: "This campaign isn't awaiting curation.",
    AlreadyClaimed: "This season's share has already been claimed.",
    UnknownRound: "Season not found.",
    RoundAlreadyOpen: "A season is already open.",
    CategoryNotInRound: "This campaign's category isn't part of this season.",
    TierTooLow: "Verification tier isn't high enough for this action.",
    NothingToClaim: "There are no funds to claim.",
    NotOwner: "Only the campaign owner can do this.",
    NotAttester: "Only a verifier can do this.",
    InvalidCid: "Invalid image CID.",
    InvalidTitle: "Invalid title.",
    rejected: "Signature cancelled.",
    generic: "Transaction failed. Try again.",
  } as Record<string, string>,
};
