/** All UI copy lives here (Bahasa-first, §10). Components import from this module, never inline strings. */
export const strings = {
  appName: "Patungan",
  nav: {
    landing: "Beranda",
    results: "Hasil",
    operator: "Operator",
  },
  landing: {
    title: "Patungan",
    subtitle: "Urunan bersama, dicocokkan secara adil.",
    poolLabel: "Dana padanan",
    sponsorLabel: "Disponsori oleh",
    sponsorName: "Pemprov Jawa Timur",
    statusOpen: "Dibuka",
    statusFinalized: "Selesai",
    roundEndLabel: "Berakhir",
    notInitialized: "Round belum dibuka",
    waitingSponsor: "Menunggu sponsor",
    donorCountSuffix: "pendukung",
    projectedMatchLabel: "Proyeksi pencocokan",
    noMatchYet: "—",
  },
  project: {
    backToLanding: "Kembali ke beranda",
    notFound: "Proyek tidak ditemukan.",
    contributeCta: "Ikut urunan",
    roundClosedCta: "Round ditutup",
    stories: {
      0: "Atap Sekolah SDN 2 bocor setiap musim hujan. Urunan ini mengganti atap seng agar anak-anak belajar dengan aman dan kering.",
      1: "Kebun Warga RW 5 memasok sayur segar untuk posyandu. Urunan ini membeli bibit dan alat tani sederhana.",
      2: "Dusun Sumber berjalan jauh setiap hari mengambil air bersih. Urunan ini mendanai sumur bor untuk warga.",
    } as Record<number, string>,
  },
  contribute: {
    title: "Urun untuk",
    amountLabel: "Pilih jumlah",
    connectFirst: "Hubungkan wallet Testnet untuk melanjutkan.",
    confirmCta: "Kirim & tanda tangani",
    awaitingSignature: "Buka Freighter untuk menandatangani…",
    submitting: "Mengirim transaksi…",
    successTitle: "Urunan berhasil!",
    viewOnExplorer: "Lihat transaksi di Explorer",
    close: "Tutup",
    cancel: "Batal",
    errors: {
      NotVerified: "Alamat belum terverifikasi.",
      RoundClosed: "Round sudah ditutup untuk kontribusi baru.",
      UnknownProject: "Proyek tidak ditemukan.",
      InvalidAmount: "Jumlah tidak valid.",
      rejected: "Tanda tangan dibatalkan.",
      generic: "Transaksi gagal. Coba lagi.",
    } as Record<string, string>,
  },
  results: {
    title: "Hasil Pencocokan",
  },
  operator: {
    title: "Konsol Operator",
    gated: "Hubungkan wallet admin untuk mengakses konsol ini.",
  },
  wallet: {
    connect: "Hubungkan Wallet",
    connecting: "Menghubungkan…",
    notInstalled: "Pasang Freighter",
    wrongNetworkPill: "Jaringan salah",
    testnetPill: "Testnet",
    wrongNetworkBanner:
      "Freighter tidak terhubung ke Testnet. Alihkan jaringan di Freighter untuk melanjutkan.",
    connectFailed: "Gagal menghubungkan wallet. Coba lagi.",
  },
  loading: "Memuat…",
  empty: "Belum ada proyek",
  errorGeneric: "Terjadi kesalahan. Coba lagi.",
  retry: "Coba lagi",
  staleData: "Gagal memuat pembaruan — menampilkan data terakhir.",
} as const;
