/** All UI copy lives here (Bahasa-first, §10). Components import from this module, never inline strings. */
export const strings = {
  appName: "Patungan",
  nav: {
    landing: "Beranda",
    results: "Hasil",
    operator: "Operator",
  },
  landing: {
    title: "Patungan",
    subtitle: "Urunan bersama, dicocokkan secara adil.",
    poolLabel: "Dana padanan",
    sponsorLabel: "Disponsori oleh",
    sponsorName: "Pemprov Jawa Timur",
    statusOpen: "Dibuka",
    statusFinalized: "Selesai",
    roundEndLabel: "Berakhir",
    notInitialized: "Round belum dibuka",
    waitingSponsor: "Menunggu sponsor",
    donorCountSuffix: "pendukung",
    projectedMatchLabel: "Proyeksi pencocokan",
    finalMatchLabel: "Pencocokan final",
    noMatchYet: "—",
  },
  project: {
    backToLanding: "Kembali ke beranda",
    notFound: "Proyek tidak ditemukan.",
    raisedLabel: "Terkumpul",
    contributeCta: "Ikut urunan",
    roundClosedCta: "Round ditutup",
    stories: {
      0: "Atap Sekolah SDN 2 bocor setiap musim hujan. Urunan ini mengganti atap seng agar anak-anak belajar dengan aman dan kering.",
      1: "Kebun Warga RW 5 memasok sayur segar untuk posyandu. Urunan ini membeli bibit dan alat tani sederhana.",
      2: "Dusun Sumber berjalan jauh setiap hari mengambil air bersih. Urunan ini mendanai sumur bor untuk warga.",
    } as Record<number, string>,
  },
  contribute: {
    title: "Urun untuk",
    amountLabel: "Pilih jumlah",
    connectFirst: "Hubungkan wallet Testnet untuk melanjutkan.",
    confirmCta: "Kirim & tanda tangani",
    awaitingSignature: "Buka Freighter untuk menandatangani…",
    submitting: "Mengirim transaksi…",
    successTitle: "Urunan berhasil!",
    viewOnExplorer: "Lihat transaksi di Explorer",
    close: "Tutup",
    cancel: "Batal",
    errors: {
      NotVerified: "Alamat belum terverifikasi.",
      RoundClosed: "Round sudah ditutup untuk kontribusi baru.",
      UnknownProject: "Proyek tidak ditemukan.",
      InvalidAmount: "Jumlah tidak valid.",
      rejected: "Tanda tangan dibatalkan.",
      generic: "Transaksi gagal. Coba lagi.",
    } as Record<string, string>,
  },
  results: {
    title: "Hasil Pencocokan",
    notFinalized: "Round belum difinalisasi — berikut proyeksi pencocokan saat ini.",
    projectLabel: "Proyek",
    directLabel: "Langsung",
    matchedLabel: "Pencocokan",
    totalLabel: "Total",
    donorSuffix: "donatur",
    verdict: "Dana padanan mengikuti jumlah orang, bukan jumlah uang.",
    hook: "Satu donatur besar vs banyak donatur kecil — lihat siapa yang menang.",
  },
  operator: {
    title: "Konsol Operator",
    gated: "Hubungkan wallet admin untuk mengakses konsol ini.",
    notAdmin: "Wallet yang terhubung bukan admin round ini.",
    awaitingSignature: "Buka Freighter untuk menandatangani…",
    submitting: "Mengirim transaksi…",
    viewOnExplorer: "Lihat transaksi di Explorer",
    fundPool: {
      heading: "Isi dana padanan",
      amountLabel: "Jumlah dana padanan",
      cta: "Kirim dana padanan",
      successTitle: "Dana padanan terkirim!",
      invalidAmount: "Masukkan jumlah bulat positif.",
    },
    verify: {
      heading: "Verifikasi alamat donatur",
      description:
        "Daftarkan wallet baru agar bisa ikut urunan — misalnya wallet juri yang ingin mencoba langsung.",
      inputLabel: "Alamat wallet (G…)",
      cta: "Verifikasi",
      successTitle: "Alamat terverifikasi!",
      invalidAddress: "Alamat Stellar tidak valid (diawali G, 56 karakter).",
    },
    finalize: {
      heading: "Finalisasi round",
      description:
        "Menutup round untuk kontribusi baru dan menghitung pencocokan kuadratik. Tidak bisa dibatalkan.",
      cta: "Finalisasi round",
      confirmMessage: "Finalisasi tidak bisa dibatalkan. Lanjutkan?",
      confirmCta: "Ya, finalisasi",
      cancelCta: "Batal",
      successTitle: "Round difinalisasi!",
      doneLabel: "Round sudah difinalisasi.",
    },
    disburse: {
      heading: "Cairkan dana ke proyek",
      cta: "Cairkan",
      disbursedLabel: "✓ Sudah dicairkan",
      needsFinalize: "Finalisasi round dahulu untuk mencairkan dana.",
    },
    errors: {
      RoundNotOpen: "Round sudah tidak dibuka untuk aksi ini.",
      AlreadyFinalized: "Round sudah difinalisasi.",
      NothingToMatch: "Belum ada kontribusi untuk dicocokkan.",
      NotFinalized: "Round belum difinalisasi.",
      UnknownProject: "Proyek tidak ditemukan.",
      AlreadyDisbursed: "Dana proyek ini sudah dicairkan.",
      InvalidAmount: "Jumlah tidak valid.",
      rejected: "Tanda tangan dibatalkan.",
      generic: "Transaksi gagal. Coba lagi.",
    } as Record<string, string>,
  },
  wallet: {
    connect: "Hubungkan Wallet",
    connecting: "Menghubungkan…",
    notInstalled: "Pasang Freighter",
    wrongNetworkPill: "Jaringan salah",
    testnetPill: "Testnet",
    wrongNetworkBanner:
      "Freighter tidak terhubung ke Testnet. Alihkan jaringan di Freighter untuk melanjutkan.",
    connectFailed: "Gagal menghubungkan wallet. Coba lagi.",
  },
  verified: {
    yes: "✓ Terverifikasi",
    no: "Belum terverifikasi",
  },
  explorer: {
    viewTx: "Lihat transaksi di Explorer",
    viewContract: "Lihat kontrak di Explorer",
  },
  footer: {
    transparency: "Setiap aksi tercatat on-chain di Stellar Testnet.",
  },
  loading: "Memuat…",
  empty: "Belum ada proyek",
  errorGeneric: "Terjadi kesalahan. Coba lagi.",
  retry: "Coba lagi",
  staleData: "Gagal memuat pembaruan — menampilkan data terakhir.",
} as const;
