import type { Strings } from "./strings.id";

/** Vietnamese UI copy — opt-in locale, shape-checked against `strings.id.ts`. */
export const vi: Strings = {
  appName: "Patungan",
  nav: {
    landing: "Trang chủ",
    campaigns: "Chiến dịch",
    seasons: "Mùa",
    results: "Kết quả",
    dashboard: "Bảng điều khiển",
    account: "Tài khoản",
    operator: "Vận hành",
    openMenu: "Mở menu",
    closeMenu: "Đóng menu",
    mainMenu: "Menu chính",
  },
  landing: {
    heroTitle: "Đóng góp nhỏ. Tác động lớn hơn.",
    heroTags: ["Ứng dụng thanh toán & tiêu dùng", "Kiều bào PMI/TKI", "Đối ứng bậc hai"],
    heroLede:
      "Ủng hộ chiến dịch từ Rp10 nghìn. Càng nhiều người tham gia, chiến dịch càng có cơ hội nhận quỹ đối ứng từ nhà tài trợ.",
    heroPoolLabel: "Quỹ đối ứng",
    heroDonorLabel: "Người ủng hộ",
    heroStatusLabel: "Trạng thái",
    waitingPool: "Đang chờ",
    primaryCta: "Xem dự án",
    secondaryCta: "Xem kết quả",
    liveProjectBadge: "Dự án live",
    waitingProjectTitle: "Đang chờ dữ liệu dự án",
    heroTopLine: (n: number) => `${n} người ủng hộ đang kéo khoản đối ứng lớn nhất.`,
    heroTopLineEmpty: "Kết nối deployment để xem dữ liệu trực tiếp.",
    matchEngineLabel: "Cỗ máy đối ứng",
    matchEngineTitle: "Chốt sổ trên Soroban",
    crowdShareLabel: "Phần dẫn đầu",
    selectedShareLabel: "Phần của chiến dịch",
    switchCampaignLabel: "Chọn chiến dịch để hiển thị",
    rankedByDirect: "Xếp theo quyên góp trong mùa này",
    ofPoolSuffix: "của quỹ đối ứng",
    proofTag: "Lớp bằng chứng Soroban",
    proofBody:
      "Blockchain không phải để trang trí: hợp đồng chứng kiến từng đóng góp, sổ đăng ký chặn sybil, và khoản chi trả đến từ phép toán ai cũng kiểm chứng được.",
    proofComment: "một mùa đối ứng trọn vẹn",
    proofSteps: [
      {
        title: "Ký quỹ quỹ đối ứng",
        copy: "Nhà tài trợ nạp vào hợp đồng, không phải tài khoản của ban tổ chức.",
      },
      {
        title: "Một danh tính, một tiếng nói",
        copy: "Sổ đăng ký đã xác minh chặn sybil: một danh tính, một tiếng nói.",
      },
      {
        title: "Quyên góp có dấu vết",
        copy: "Mỗi khoản góp được ghi kèm donor, project_id, amount và ledger.",
      },
      {
        title: "Phân bổ bậc hai",
        copy: "Hợp đồng tính (Σ√c)² cho từng chiến dịch và chia quỹ đối ứng — số người thắng, không phải một cá voi.",
      },
    ],
    directoryComment: "danh bạ công khai — mọi chiến dịch đều được giám tuyển xác minh",
    seasonRef: (id: string | number) => `mùa #${id}`,
    title: "Patungan",
    subtitle: "Cùng nhau đóng góp, được đối ứng công bằng.",
    poolLabel: "Quỹ đối ứng",
    sponsorLabel: "Được tài trợ bởi",
    sponsorName: "Pemprov Jawa Timur",
    statusOpen: "Đang mở",
    statusFinalized: "Đã hoàn tất",
    roundEndLabel: "Kết thúc",
    notInitialized: "Chưa mở mùa nào",
    waitingSponsor: "Đang chờ nhà tài trợ",
    donorCountSuffix: "người ủng hộ",
    projectedMatchLabel: "Dự kiến đối ứng",
    finalMatchLabel: "Đối ứng cuối cùng",
    noMatchYet: "—",
  },
  categories: {
    DevelopingRegions: "Khu vực đang phát triển",
    DisasterRelief: "Cứu trợ thiên tai",
    EducationHealth: "Giáo dục & Y tế",
  } as Record<string, string>,
  discovery: {
    heading: "Khám phá chiến dịch",
    tagline: "Sự ủng hộ nhỏ từ nhiều người, được đối ứng công bằng.",
    searchPlaceholder: "Tìm chiến dịch…",
    searchLabel: "Tìm chiến dịch theo tiêu đề hoặc câu chuyện",
    sortLabel: "Sắp xếp",
    sort: {
      mostBacked: "Được ủng hộ nhiều nhất",
      newest: "Mới nhất",
      closingSoon: "Sắp kết thúc",
    },
    allFilter: "Tất cả",
    createCta: "Gửi chiến dịch",
    resultCount: (n: number) => `${n} chiến dịch`,
    emptyApproved: "Chưa có chiến dịch nào được duyệt.",
    emptyFiltered: "Không có chiến dịch nào khớp với bộ lọc này.",
    resetFilters: "Đặt lại bộ lọc",
    // Season / round banner
    season: "Mùa đối ứng",
    live: "Đang diễn ra",
    scopeAll: "Tất cả danh mục",
    scopeLabel: "Danh mục trong mùa này",
    endsInLabel: "Kết thúc sau",
    endedLabel: "Mùa đã kết thúc",
    noRound: "Không có mùa đối ứng nào đang hoạt động",
    noRoundHint: "Quyên góp trực tiếp vẫn mở. Mùa tiếp theo sắp bắt đầu.",
    countdown: { day: " ngày", hour: " giờ", min: " phút", ended: "Đã kết thúc" },
    // Card
    donorSuffix: "người ủng hộ",
    donorLabel: "Người ủng hộ",
    directShort: "Trực tiếp",
    projectedShort: "Dự kiến",
    projectedHint: "Ước tính có thể thay đổi cho đến khi mùa đối ứng được hoàn tất.",
    totalShort: "Tổng",
    matchSuffix: "đối ứng",
    cardDirectOpen: "Quyên góp trực tiếp vẫn mở",
    targetProgress: "hướng tới mục tiêu",
    targetReached: "Đã đạt mục tiêu",
    noThumbAlt: "Không có ảnh",
    // Onboarding "how it works" strip — QF explainer for cold visitors
    howItWorks: {
      overline: "Cách hoạt động",
      steps: [
        {
          n: "01",
          title: "Quyên góp trực tiếp, bất cứ lúc nào",
          body: "Chọn một chiến dịch bạn tin tưởng, rồi quyên góp trực tiếp — không cần chờ đến mùa.",
        },
        {
          n: "02",
          title: "Số lượng người, không phải số tiền",
          body: "Nhiều người ủng hộ nhỏ tạo tín hiệu mạnh hơn một người ủng hộ lớn.",
        },
        {
          n: "03",
          title: "Quỹ đối ứng được chia mỗi mùa",
          body: "Cuối mỗi mùa, quỹ tài trợ được chia theo tín hiệu đó, theo cách bậc hai (quadratic).",
        },
      ],
      viz: {
        crowd: "nhiều người ủng hộ nhỏ",
        whale: "một người ủng hộ lớn",
        beats: "mạnh hơn",
        sr: "Nhiều người ủng hộ nhỏ mạnh hơn một người ủng hộ lớn.",
      },
    },
  },
  campaign: {
    back: "Quay lại khám phá",
    notFoundTitle: "Không tìm thấy chiến dịch",
    notFoundBody: "Chiến dịch này có thể chưa tồn tại, hoặc liên kết không đúng.",
    backHome: "Về trang chủ",
    byOwner: "Điều hành bởi",
    organizer: {
      heading: "Người tổ chức",
      viewWallet: "Xem ví",
      firstCampaign: "Chiến dịch đầu tiên trên Patungan",
      campaignCount: (n: number) => `${n} chiến dịch trên Patungan`,
      raisedAcross: "quyên góp được trên tất cả",
      otherHeading: "Chiến dịch khác của người tổ chức này",
      verifiedDomain: "Tên miền đã xác minh",
      curatorNote: "Mọi chiến dịch hiển thị đều được người kiểm duyệt phê duyệt trước khi nhận quyên góp.",
    },
    transparencyHeading: "Minh bạch giải ngân",
    verifiedLabel: "Trạng thái chiến dịch",
    verifiedValue: "Đã được giám tuyển xác minh",
    payoutRecipientLabel: "Người nhận tiền",
    payoutScheduleLabel: "Thời điểm giải ngân",
    payoutScheduleValue:
      "Chủ chiến dịch có thể nhận quyên góp trực tiếp; quỹ đối ứng có sau khi mùa được hoàn tất.",
    storyHeading: "Về chiến dịch này",
    raisedLabel: "Tổng quyên góp trực tiếp",
    thisRoundHeading: "Mùa đối ứng này",
    donorSuffix: "người ủng hộ",
    projectedMatchLabel: "Dự kiến đối ứng bậc hai",
    notInRound:
      "Chưa thuộc mùa đối ứng đang hoạt động — quyên góp trực tiếp vẫn được tính cho đối ứng của mùa tiếp theo.",
    /** Notice shown when a non-Approved campaign is opened directly (owner-shared link). */
    status: {
      Pending: "Chiến dịch này vẫn đang chờ kiểm duyệt. Quyên góp sẽ mở sau khi người kiểm duyệt phê duyệt.",
      Rejected: "Chiến dịch này không qua kiểm duyệt và không thể nhận quyên góp.",
      Cancelled: "Chiến dịch này đã bị hủy.",
    } as Record<string, string>,
    create: {
      back: "Quay lại khám phá",
      heading: "Gửi chiến dịch",
      subtitle:
        "Kể câu chuyện chiến dịch của bạn, tải lên một hình ảnh, rồi gửi để kiểm duyệt. Sau khi người kiểm duyệt phê duyệt, chiến dịch sẽ công khai và có thể nhận quyên góp.",
      // Gate ladder (mirrors the contribute gate)
      connectPrompt: "Kết nối ví Testnet để gửi chiến dịch.",
      wrongNetwork: "Chuyển Freighter sang Testnet để tiếp tục.",
      tierGateTitle: "Xác minh trước",
      tierGateBody: "Bạn cần xác minh cấp Basic để gửi chiến dịch.",
      tierGateCta: "Xác minh ngay",
      // Fields
      titleLabel: "Tiêu đề chiến dịch",
      titlePlaceholder: "vd. Giếng nước sạch cho Dusun Sumber",
      categoryLabel: "Danh mục",
      storyLabel: "Câu chuyện chiến dịch",
      storyPlaceholder: "Giải thích ai được giúp đỡ, tài trợ cho việc gì, và tại sao điều đó quan trọng.",
      payoutLabel: "Địa chỉ nhận tiền",
      payoutHelper: "Mặc định: ví của bạn. Số tiền quyên góp được sẽ chuyển đến địa chỉ này.",
      payoutReset: "Dùng ví của tôi",
      imageLabel: "Hình ảnh chiến dịch",
      // Image dropzone
      image: {
        dropPrompt: "Kéo ảnh vào đây hoặc chọn tệp",
        dropHint: "PNG hoặc JPG, được ghim lên IPFS",
        pickFile: "Chọn tệp",
        uploading: "Đang tải ảnh lên…",
        replace: "Thay ảnh",
        remove: "Xóa",
        cidLabel: "CID",
        errorFallback: "Không thể ghim ảnh. Thử lại.",
        previewAlt: "Xem trước ảnh chiến dịch",
      },
      // Client-side validation
      invalid: {
        titleRequired: "Cần nhập tiêu đề.",
        titleTooLong: "Tiêu đề tối đa 96 ký tự.",
        storyRequired: "Cần nhập câu chuyện.",
        storyTooLong: "Câu chuyện tối đa 1024 ký tự.",
        payoutInvalid: "Địa chỉ Stellar không hợp lệ (phải bắt đầu bằng G, 56 ký tự).",
        imageRequired: "Tải lên một hình ảnh chiến dịch.",
      } as Record<string, string>,
      // Submit tx
      submit: "Gửi để kiểm duyệt",
      awaiting: "Mở Freighter để ký…",
      submitting: "Đang gửi giao dịch…",
      // Success
      successTitle: "Đã gửi chiến dịch — đang chờ kiểm duyệt",
      successBody:
        "Chiến dịch của bạn đã được ghi lại on-chain với trạng thái Đang chờ kiểm duyệt. Sau khi người kiểm duyệt phê duyệt, chiến dịch sẽ công khai và có thể nhận quyên góp.",
      viewCampaign: "Xem chiến dịch",
      createAnother: "Gửi chiến dịch khác",
    },
    jejak: {
      tag: "Dấu vết on-chain",
      heading: "Rp50 nghìn của bạn đi đâu",
      steps: [
        "Khoản quyên góp của bạn được ghi vào hợp đồng kèm địa chỉ, số tiền và ledger.",
        "Đóng góp của bạn nâng trọng số (Σ√c)² của chiến dịch — tín hiệu công khai, không phải lời hứa.",
        "Cuối mùa, quỹ đối ứng được chia theo tín hiệu đó. Ai cũng có thể kiểm chứng.",
      ],
      artifactsLabel: (id: number) => `Hiện vật chiến dịch #${id}`,
      categoryLabel: "danh mục",
    },
    ledger: {
      heading: "Hoạt động chiến dịch",
      body: "Mọi khoản quyên góp vào và mọi khoản chi trả cho chủ sở hữu — dựng lại thẳng từ event log của hợp đồng, không có backend ở giữa.",
      empty: "Chưa có hoạt động on-chain nào trong cửa sổ lưu trữ RPC.",
      retention: "Chỉ hiển thị các sự kiện trong cửa sổ lưu trữ RPC Testnet.",
      filterAll: "Tất cả",
      filterIn: "Quyên góp",
      filterOut: "Chi trả",
      summaryIn: "đã quyên góp",
      summaryOut: "chi cho chủ sở hữu",
      payoutLabel: "Đã chuyển cho chủ sở hữu",
      roundTag: (r: number) => `vòng #${r}`,
      showMore: "Xem thêm",
      showLess: "Thu gọn",
    },
    contribute: {
      cta: "Cùng góp",
      amountLabel: "Chọn số tiền",
      customChip: "Số tiền khác",
      customPlaceholder: "vd. 25000",
      customInvalid: "Nhập một số nguyên dương.",
      confirm: "Xem lại khoản góp",
      reviewTitle: "Xem lại trước khi ký",
      reviewBody:
        "Freighter sẽ yêu cầu chữ ký sau khi xác nhận. Hãy kiểm tra số tiền, chiến dịch và người nhận.",
      reviewCampaign: "Chiến dịch",
      reviewAmount: "Số tiền đóng góp",
      reviewRecipient: "Người nhận",
      reviewNetwork: "Mạng",
      reviewSubmit: "Xác nhận & mở Freighter",
      reviewBack: "Đổi số tiền",
      awaiting: "Mở Freighter để ký…",
      submitting: "Đang gửi giao dịch…",
      successTitle: "Cảm ơn — đóng góp của bạn đã được ghi on-chain.",
      done: "Xong",
      cancel: "Hủy",
      connectPrompt: "Kết nối ví Testnet để cùng góp.",
      wrongNetwork: "Chuyển Freighter sang Testnet để tiếp tục.",
      tierGateTitle: "Xác minh trước",
      tierGateBody: "Bạn cần xác minh cấp Basic để cùng góp.",
      tierGateCta: "Xác minh ngay",
    },
  },
  project: {
    backToLanding: "Về trang chủ",
    notFound: "Không tìm thấy dự án.",
    raisedLabel: "Đã quyên góp",
    contributeCta: "Cùng góp",
    roundClosedCta: "Vòng đã đóng",
    stories: {
      0: "Mái trường Tiểu học SDN 2 bị dột mỗi mùa mưa. Quỹ này thay mái tôn mới để trẻ em học tập an toàn và khô ráo.",
      1: "Vườn cộng đồng RW 5 cung cấp rau tươi cho trạm y tế địa phương. Quỹ này mua hạt giống và dụng cụ làm vườn cơ bản.",
      2: "Người dân Dusun Sumber phải đi bộ rất xa mỗi ngày để lấy nước sạch. Quỹ này chi trả cho việc khoan giếng cho cộng đồng.",
    } as Record<number, string>,
  },
  contribute: {
    title: "Đóng góp cho",
    amountLabel: "Chọn số tiền",
    connectFirst: "Kết nối ví Testnet để tiếp tục.",
    confirmCta: "Gửi & ký",
    awaitingSignature: "Mở Freighter để ký…",
    submitting: "Đang gửi giao dịch…",
    successTitle: "Đóng góp thành công!",
    viewOnExplorer: "Xem giao dịch trên Explorer",
    close: "Đóng",
    cancel: "Hủy",
    errors: {
      NotVerified: "Địa chỉ này chưa được xác minh.",
      RoundClosed: "Mùa này đã đóng, không nhận đóng góp mới.",
      UnknownProject: "Không tìm thấy dự án.",
      InvalidAmount: "Số tiền không hợp lệ.",
      rejected: "Đã hủy ký.",
      generic: "Giao dịch thất bại. Thử lại.",
    } as Record<string, string>,
  },
  seasons: {
    title: "Lưu trữ các mùa",
    subtitle: "Mọi mùa đối ứng từng mở, mới nhất trước. Các mùa đã kết thúc hiển thị chiến dịch có mức đối ứng lớn nhất.",
    seasonLabel: (id: number) => `Mùa #${id}`,
    poolLabel: "Quỹ đối ứng",
    sponsorLabel: "Nhà tài trợ",
    scopeLabel: "Danh mục",
    scopeAll: "Tất cả danh mục",
    // Status pills (reuse the dashboard tones)
    status: {
      Open: "Đang diễn ra",
      Finalized: "Đã kết thúc",
      Cancelled: "Đã hủy",
    } as Record<string, string>,
    // Open round line
    liveEndsIn: "Kết thúc sau",
    liveEnded: "Đang chờ hoàn tất",
    liveProjection: "Dự kiến đối ứng trực tiếp",
    countdown: { day: " ngày", hour: " giờ", min: " phút", ended: "Đã kết thúc" },
    // Finalized leaderboard
    topHeading: "Đối ứng lớn nhất",
    noMatches: "Không có chiến dịch nào được đối ứng trong mùa này.",
    cancelledNote: "Mùa này đã bị hủy trước khi hoàn tất. Quỹ đã được hoàn lại cho nhà tài trợ.",
    viewResults: "Xem kết quả",
    // States
    empty: "Chưa có mùa đối ứng nào.",
    emptyHint: "Mùa đầu tiên sẽ xuất hiện ở đây khi nhà tài trợ mở một vòng.",
  },
  results: {
    title: "Kết quả đối ứng",
    seasonLabel: (id: number) => `Mùa #${id}`,
    notFinalized: "Mùa này chưa hoàn tất. Đây là mức đối ứng dự kiến dựa trên các đóng góp hiện tại.",
    finalized: "Kết quả cuối cùng của mùa này.",
    roundPickerLabel: "Mùa",
    directLabel: "Trực tiếp",
    matchedLabel: "Đối ứng",
    directDefinition: "Trực tiếp: khoản quyên góp thực tế từ người ủng hộ trong mùa này.",
    matchedDefinition: "Đối ứng: phần bổ sung từ quỹ tài trợ, được chia theo công thức bậc hai.",
    barHint: "Độ dài thanh là tổng tiền; màu sắc cho biết nguồn tiền.",
    openCampaign: "Mở chiến dịch",
    donorSuffix: "người ủng hộ",
    poolLabel: "Quỹ đối ứng",
    totalMatchedLabel: "Tổng quỹ đối ứng đã phân phối",
    verdict: "Quỹ đối ứng theo số lượng người ủng hộ, không theo số tiền đóng góp.",
    // States
    empty: "Chưa có đóng góp nào để đối ứng trong mùa này.",
    emptyHint: "Kết quả sẽ xuất hiện khi các chiến dịch nhận được quyên góp trong mùa này.",
    notFoundTitle: "Không tìm thấy mùa",
    notFoundBody: "Mùa này có thể chưa tồn tại, hoặc liên kết không đúng.",
    backToSeasons: "Xem lưu trữ các mùa",
    noRounds: "Chưa có mùa đối ứng nào.",
    barLabel: "So sánh quyên góp trực tiếp và quỹ đối ứng",
    slowLoad: "Dữ liệu on-chain đang tải lâu hơn bình thường.",
  },
  operator: {
    title: "Bảng điều khiển Vận hành",
    subtitle: "Vận hành trọn một mùa đối ứng: mở vòng, cấp quỹ, kiểm duyệt chiến dịch, rồi hoàn tất.",
    // Gate ladder
    connectPrompt: "Kết nối ví vận hành để truy cập bảng điều khiển này.",
    notRole: "Ví đang kết nối không giữ vai trò vận hành (quản trị viên, người kiểm duyệt, hoặc người xác minh).",
    wrongNetwork: "Chuyển Freighter sang Testnet để tiếp tục.",
    // Shared tx phases
    awaiting: "Mở Freighter để ký…",
    submitting: "Đang gửi giao dịch…",
    // Status strip — the anchor every action is read against
    status: {
      connectedAs: "Đã kết nối với vai trò",
      roles: "Vai trò",
      roleAdmin: "Quản trị viên",
      roleCurator: "Người kiểm duyệt",
      roleAttester: "Người xác minh",
      liveRound: "Mùa đang diễn ra",
      noRound: "Không có mùa nào đang mở",
      poolLabel: "Quỹ đối ứng",
      scopeAll: "Tất cả danh mục",
      endsLabel: "Kết thúc",
      ended: "Đã kết thúc",
    },
    // Region headings
    lifecycleHeading: "Mùa đối ứng",
    governanceHeading: "Quản trị",
    // Section overlines / step numbers
    step: { open: "01 · Mở mùa", fund: "02 · Cấp quỹ", finalize: "03 · Hoàn tất" },
    // 1 · Open round
    open: {
      heading: "Mở một mùa đối ứng",
      description: "Bắt đầu mùa mới: đặt ngày kết thúc và các danh mục được đối ứng. Chỉ một mùa được mở tại một thời điểm.",
      endLabel: "Ngày kết thúc",
      endHelper: "Hiển thị cho người quyên góp dưới dạng đếm ngược.",
      categoriesLabel: "Danh mục trong mùa này",
      categoriesHint: "Để trống để đối ứng mọi danh mục.",
      cta: "Mở mùa",
      successTitle: "Đã mở mùa!",
      alreadyOpen: (id: number) => `Mùa #${id} đang diễn ra. Hoàn tất mùa đó trước khi mở mùa mới.`,
      invalidDate: "Chọn ngày kết thúc trong tương lai.",
    },
    // 2 · Fund pool
    fund: {
      heading: "Cấp quỹ đối ứng",
      description: "Nạp quỹ đối ứng cho mùa đang diễn ra. Yêu cầu xác minh cấp Institution.",
      amountLabel: "Số tiền quỹ (IDR)",
      echoLabel: "Sẽ nạp",
      cta: "Gửi quỹ",
      successTitle: "Đã gửi quỹ đối ứng!",
      invalidAmount: "Nhập một số nguyên dương.",
      needsRound: "Mở một mùa trước khi cấp quỹ.",
      tierGateTitle: "Cần cấp Institution",
      tierGateBody:
        "Chỉ những ví đã xác minh cấp Institution mới có thể cấp quỹ đối ứng. Dùng bảng xác minh bên dưới để nâng cấp ví này.",
    },
    // 3 · Finalize
    finalize: {
      heading: "Hoàn tất mùa",
      description: "Đóng mùa với các đóng góp mới và tính toán đối ứng bậc hai. Không thể hoàn tác.",
      cta: "Hoàn tất mùa",
      confirmMessage: "Việc hoàn tất không thể hoàn tác. Tiếp tục?",
      confirmCta: "Có, hoàn tất ngay",
      cancelCta: "Hủy",
      successTitle: "Đã hoàn tất mùa!",
      viewResults: "Xem kết quả",
      needsRound: "Không có mùa nào đang mở để hoàn tất.",
    },
    // 4 · Curation queue
    curation: {
      heading: "Hàng đợi kiểm duyệt",
      description: "Các chiến dịch mới đang chờ phê duyệt trước khi công khai và có thể nhận quyên góp.",
      empty: "Không có chiến dịch nào đang chờ kiểm duyệt.",
      pendingBadge: "Đang chờ",
      approve: "Phê duyệt",
      reject: "Từ chối",
      approving: "Đang phê duyệt…",
      rejecting: "Đang từ chối…",
      byOwner: "Bởi",
      approvedToast: "Đã phê duyệt chiến dịch.",
      rejectedToast: "Đã từ chối chiến dịch.",
    },
    // 5 · Verify fallback
    verify: {
      heading: "Xác minh thủ công",
      description: "Đặt cấp xác minh cho một địa chỉ — cách thay thế trên testnet cho trình xác thực KYC.",
      addressLabel: "Địa chỉ ví (G…)",
      tierLabel: "Cấp độ",
      tiers: { None: "Không có", Basic: "Basic", Institution: "Institution" } as Record<string, string>,
      cta: "Đặt cấp độ",
      successTitle: "Đã đặt cấp xác minh!",
      invalidAddress: "Địa chỉ Stellar không hợp lệ (phải bắt đầu bằng G, 56 ký tự).",
    },
    viewOnExplorer: "Xem giao dịch trên Explorer",
    /** Error overrides specific to operator actions; anything omitted falls back to shared strings.errors. */
    errors: {
      RoundAlreadyOpen: "Đã có một mùa đang diễn ra.",
      RoundNotOpen: "Mùa này không còn mở cho hành động này.",
      AlreadyFinalized: "Mùa này đã được hoàn tất.",
      NothingToMatch: "Chưa có đóng góp nào để đối ứng.",
      TierTooLow: "Cấp xác minh chưa đủ (cần cấp Institution).",
      NotAdmin: "Chỉ quản trị viên mới có thể thực hiện việc này.",
      NotCurator: "Chỉ người kiểm duyệt mới có thể thực hiện việc này.",
      NotAttester: "Chỉ người xác minh mới có thể thực hiện việc này.",
      ProjectNotPending: "Chiến dịch này không đang chờ kiểm duyệt.",
      InvalidAmount: "Số tiền không hợp lệ.",
      rejected: "Đã hủy ký.",
      generic: "Giao dịch thất bại. Thử lại.",
    } as Record<string, string>,
  },
  dashboard: {
    title: "Bảng điều khiển của tôi",
    subtitle: "Các chiến dịch bạn đã gửi, tổng quyên góp nhận được, và khoản thanh toán đối ứng mỗi mùa.",
    createCta: "Gửi chiến dịch",
    summary: { campaigns: "Tổng chiến dịch", active: "Đang hoạt động", raised: "Tổng quyên góp", claimable: "Có thể nhận" },
    filters: {
      label: "Lọc chiến dịch",
      all: "Tất cả",
      active: "Đang hoạt động",
      pending: "Đang chờ",
      action: "Cần xử lý",
      empty: "Không có chiến dịch nào trong bộ lọc này.",
    },
    actionCenter: {
      title: "Có tiền sẵn sàng nhận",
      body: (n: number) => `${n} chiến dịch có quyên góp ngoài mùa đang chờ bạn xử lý.`,
      cta: "Xem ngay",
    },
    insights: {
      show: "Xem phân tích",
      hide: "Đóng phân tích",
      trend: "Xu hướng quyên góp gần đây",
      activity: "Hoạt động gần đây",
      empty: "Chưa có sự kiện quyên góp trong cửa sổ lưu trữ Testnet.",
      donor: "Người ủng hộ",
      viewTx: "Xem giao dịch",
    },
    // Gate ladder (owners need no verification tier — just a Testnet wallet)
    connectPrompt: "Kết nối ví Testnet để xem các chiến dịch của bạn.",
    wrongNetwork: "Chuyển Freighter sang Testnet để tiếp tục.",
    // Empty state
    empty: "Bạn chưa có chiến dịch nào.",
    emptyHint: "Gửi chiến dịch đầu tiên của bạn để bắt đầu nhận quyên góp và quỹ đối ứng.",
    // Per-campaign
    statusPill: {
      Pending: "Đang chờ kiểm duyệt",
      Approved: "Đang hoạt động",
      Rejected: "Đã từ chối",
      Cancelled: "Đã hủy",
    } as Record<string, string>,
    lifetimeLabel: "Tổng quyên góp trực tiếp",
    seasonsHeading: "Thanh toán theo mùa",
    seasonsLoading: "Đang tải khoản thanh toán…",
    noSeasons: "Chiến dịch này chưa từng thuộc một mùa đối ứng đã hoàn tất.",
    // Per finalized round
    round: {
      label: (id: number) => `Mùa #${id}`,
      directLabel: "Trực tiếp",
      donorSuffix: "người ủng hộ",
      matchedLabel: "Đối ứng",
      claim: "Nhận quỹ đối ứng",
      claiming: "Đang nhận…",
      claimed: "Đã nhận",
      nothing: "Không có đối ứng trong mùa này",
    },
    // Campaign-level claim of donations received while no round was open
    direct: {
      heading: "Quyên góp ngoài mùa",
      body: "Các khoản quyên góp nhận được khi không có mùa nào hoạt động — có thể nhận bất cứ lúc nào.",
      claim: "Nhận quyên góp trực tiếp",
      claiming: "Đang nhận…",
      claimed: "Đã giải ngân quyên góp trực tiếp.",
    },
    // Shared tx phases
    awaiting: "Mở Freighter để ký…",
    submitting: "Đang gửi giao dịch…",
    claimedTitle: "Đã nhận quỹ thành công!",
    viewOnExplorer: "Xem giao dịch trên Explorer",
  },
  account: {
    title: "Đóng góp của tôi",
    subtitle: "Lịch sử quyên góp trực tiếp của bạn, được dựng lại từ dữ liệu on-chain — nhóm theo chiến dịch.",
    // Gate ladder (a contributor only needs a Testnet wallet to see their own history)
    connectPrompt: "Kết nối ví Testnet để xem lịch sử đóng góp của bạn.",
    wrongNetwork: "Chuyển Freighter sang Testnet để tiếp tục.",
    // Header ledger figure (quiet total, not a hero card)
    tierLabel: "Xác minh",
    tier: { None: "Chưa xác minh", Basic: "Basic", Institution: "Institution" } as Record<
      string,
      string
    >,
    impactLabel: "Tổng tác động của tôi",
    campaignCount: (n: number) => `${n} chiến dịch`,
    giftCount: (n: number) => `${n} lần quyên góp`,
    // Per-campaign group
    myTotalLabel: "Đóng góp của tôi",
    unknownCampaign: (id: number) => `Chiến dịch #${id}`,
    viewCampaign: "Xem chiến dịch",
    viewTx: "Xem trên Explorer",
    // Empty state
    empty: "Bạn chưa quyên góp lần nào.",
    emptyHint: "Khoản quyên góp đầu tiên của bạn sẽ xuất hiện ở đây, được ghi trực tiếp từ giao dịch on-chain.",
    exploreCta: "Khám phá chiến dịch",
    // Retention caveat — testnet RPC prunes old events; keep the reconstruction honest.
    retentionNote: "Chỉ những khoản quyên góp trong cửa sổ lưu trữ của Testnet RPC mới có thể hiển thị.",
  },
  /** Tier-aware verification badge labels + one-line unlock captions (`TierBadge`). */
  tierBadge: {
    currentLabel: "Cấp xác minh của bạn",
    tiers: {
      None: "Chưa xác minh",
      Basic: "Đã xác minh Basic",
      Institution: "Đã xác minh Institution",
    } as Record<string, string>,
    unlocks: {
      None: "Xác minh để bắt đầu đóng góp và gửi chiến dịch.",
      Basic: "Bạn có thể đóng góp và gửi chiến dịch.",
      Institution: "Bạn có thể đóng góp, gửi chiến dịch, và cấp quỹ đối ứng.",
    } as Record<string, string>,
  },
  verify: {
    title: "Xác minh",
    subtitle:
      "Xác minh một lần để mở khóa đóng góp và gửi chiến dịch. Dữ liệu danh tính của bạn không bao giờ được lưu ở đây — chỉ cấp xác minh được ghi on-chain.",
    // Gate ladder
    connectPrompt: "Kết nối ví Testnet để bắt đầu xác minh.",
    wrongNetwork: "Chuyển Freighter sang Testnet để tiếp tục.",
    // What each tier unlocks — the ladder rail
    ladderHeading: "Những gì mỗi cấp mở khóa",
    ladder: [
      { tier: "Basic", unlock: "Đóng góp & gửi chiến dịch" },
      { tier: "Institution", unlock: "Cấp quỹ đối ứng với vai trò nhà tài trợ" },
    ],
    // Step 1 — SEP-10 ownership
    sep10: {
      overline: "01 · Chứng minh quyền sở hữu",
      heading: "Chứng minh bạn sở hữu ví này",
      description: "Ký thử thách từ trình xác thực (SEP-10) để chứng minh quyền sở hữu ví. Không có khoản tiền nào di chuyển.",
      cta: "Bắt đầu chứng minh quyền sở hữu",
      pending: "Đang liên hệ trình xác thực…",
      awaiting: "Mở Freighter để ký…",
      successTitle: "Đã chứng minh quyền sở hữu",
      successBody: "Trình xác thực đã cấp mã phiên. Tiếp tục sang bước đặt cấp độ.",
      notConfiguredTitle: "Trình xác thực chưa được cấu hình",
      notConfiguredBody:
        "Chưa có trình xác thực SEP-10 nào được kết nối trong môi trường này. Bạn vẫn có thể dùng cách đặt cấp độ mô phỏng trên testnet bên dưới.",
      errors: {
        "not-configured": "Không có trình xác thực nào được cấu hình trong môi trường này.",
        toml: "Không tìm thấy endpoint SEP-10 của trình xác thực.",
        challenge: "Trình xác thực từ chối yêu cầu xác minh. Thử lại.",
        "invalid-challenge": "Thử thách của trình xác thực không hợp lệ.",
        signature: "Đã hủy ký.",
        token: "Trình xác thực từ chối chữ ký. Thử lại.",
        network: "Không thể liên hệ trình xác thực. Kiểm tra kết nối rồi thử lại.",
        generic: "Xác minh với trình xác thực thất bại. Thử lại.",
      } as Record<string, string>,
    },
    // Step 1.5 — SEP-12 KYC fields (real, only when the anchor publishes a KYC_SERVER)
    kyc: {
      overline: "01b · Thông tin KYC",
      heading: "Gửi thông tin KYC đến trình xác thực",
      description: "Trình xác thực này cung cấp dịch vụ KYC (SEP-12). Điền một vài thông tin để trình xác thực xem xét.",
      firstName: "Tên",
      lastName: "Họ",
      email: "Email",
      cta: "Gửi đến trình xác thực",
      submitting: "Đang gửi đến trình xác thực…",
      polling: "Đang kiểm tra trạng thái với trình xác thực…",
      status: {
        NEEDS_INFO: "Trình xác thực cần thêm thông tin.",
        PROCESSING: "Trình xác thực đang xử lý hồ sơ của bạn.",
        PENDING: "Đang chờ quyết định của trình xác thực.",
        ACCEPTED: "Trình xác thực đã chấp nhận KYC của bạn. Tiếp tục sang bước đặt cấp độ.",
        REJECTED: "Trình xác thực đã từ chối hồ sơ KYC này.",
      } as Record<string, string>,
      errors: {
        "not-configured": "Không có trình xác thực nào được cấu hình trong môi trường này.",
        "kyc-not-configured":
          "Trình xác thực này không cung cấp dịch vụ KYC (SEP-12) — tiếp tục qua cách đặt cấp độ mô phỏng trên testnet bên dưới.",
        "kyc-rejected": "Trình xác thực đã từ chối hồ sơ KYC. Thử lại.",
        network: "Không thể liên hệ trình xác thực. Kiểm tra kết nối rồi thử lại.",
        generic: "Gửi hồ sơ KYC thất bại. Thử lại.",
      } as Record<string, string>,
    },
    // Step 2 — attest (real KYC hand-off, or the simulated testnet stand-in)
    attest: {
      overline: "02 · Đặt cấp độ",
      heading: "Nhận cấp xác minh của bạn",
      simBadge: "Mô phỏng testnet",
      realBadge: "Đã chấp nhận KYC từ trình xác thực",
      description:
        "Trong môi trường thực tế, trình xác thực phê duyệt KYC rồi ghi cấp độ của bạn. Trên testnet, người vận hành (giữ vai trò người xác minh) thay thế trình xác thực.",
      // Attester-holder path (self-serve on testnet)
      attesterHint: "Ví này giữ vai trò người xác minh — bạn có thể đặt cấp độ trực tiếp với tư cách thay thế trình xác thực.",
      tierLabel: "Cấp độ",
      tiers: { Basic: "Basic", Institution: "Institution" } as Record<string, string>,
      cta: "Phê duyệt (KYC mô phỏng)",
      successTitle: "Đã đặt cấp xác minh!",
      // Non-attester fallback
      fallbackTitle: "Đang chờ người vận hành đặt cấp độ",
      fallbackBody:
        "Trên testnet, việc đặt cấp độ do người vận hành xử lý thay cho trình xác thực. Quyền sở hữu ví của bạn đã được chứng minh — hãy yêu cầu người vận hành đặt cấp độ của bạn qua bảng điều khiển.",
      fallbackCta: "Mở bảng điều khiển vận hành",
      alreadyTitle: "Bạn đã được xác minh",
      alreadyBody: "Không cần làm gì thêm. Bạn đã sẵn sàng đóng góp.",
      exploreCta: "Khám phá chiến dịch",
    },
    // Shared tx phases
    submitting: "Đang gửi giao dịch…",
    viewOnExplorer: "Xem giao dịch trên Explorer",
    tierError: "Không tải được cấp xác minh. Thử lại.",
  },
  wallet: {
    connect: "Kết nối ví",
    connecting: "Đang kết nối…",
    disconnect: "Ngắt kết nối ví",
    notInstalled: "Cài đặt Freighter",
    wrongNetworkPill: "Sai mạng",
    testnetPill: "Testnet",
    wrongNetworkBanner: "Freighter chưa kết nối với Testnet. Chuyển mạng trong Freighter để tiếp tục.",
    connectFailed: "Kết nối ví thất bại. Thử lại.",
  },
  explorer: {
    viewTx: "Xem giao dịch trên Explorer",
    viewContract: "Xem hợp đồng trên Explorer",
  },
  footer: {
    transparency: "Mọi hành động đều được ghi lại on-chain trên Stellar Testnet.",
  },
  notFound: {
    title: "Không tìm thấy trang",
    body: "Tuyến đường này không có trong sổ cái. Kiểm tra liên kết, hoặc quay về trang chủ.",
    cta: "Về trang chủ",
  },
  loading: "Đang tải…",
  empty: "Chưa có dự án nào",
  errorGeneric: "Đã có lỗi xảy ra. Thử lại.",
  retry: "Thử lại",
  staleData: "Không tải được cập nhật — đang hiển thị dữ liệu gần nhất.",
  /**
   * Shared Vietnamese fallback for every contract `Error` variant (mapped by name via
   * `mapContractError`). Context-specific screens may override individual keys by passing their
   * own map; anything they omit falls back here, so no rejection ever renders raw internals.
   */
  errors: {
    AlreadyInitialized: "Hợp đồng đã được khởi tạo.",
    NotAdmin: "Chỉ quản trị viên mới có thể thực hiện việc này.",
    NotVerified: "Địa chỉ này chưa được xác minh.",
    RoundClosed: "Mùa này đã đóng, không nhận đóng góp mới.",
    RoundNotOpen: "Mùa này không còn mở cho hành động này.",
    AlreadyFinalized: "Mùa này đã được hoàn tất.",
    NotFinalized: "Mùa này chưa hoàn tất.",
    UnknownProject: "Không tìm thấy chiến dịch.",
    DuplicateProject: "Chiến dịch này đã được đăng ký.",
    AlreadyDisbursed: "Quỹ của chiến dịch này đã được giải ngân.",
    InvalidAmount: "Số tiền không hợp lệ.",
    NothingToMatch: "Chưa có đóng góp nào để đối ứng.",
    NotCurator: "Chỉ người kiểm duyệt mới có thể thực hiện việc này.",
    ProjectNotApproved: "Chiến dịch này chưa được người kiểm duyệt phê duyệt.",
    ProjectNotPending: "Chiến dịch này không đang chờ kiểm duyệt.",
    AlreadyClaimed: "Phần của mùa này đã được nhận.",
    UnknownRound: "Không tìm thấy mùa.",
    RoundAlreadyOpen: "Đã có một mùa đang mở.",
    CategoryNotInRound: "Danh mục của chiến dịch này không thuộc mùa này.",
    TierTooLow: "Cấp xác minh chưa đủ cho hành động này.",
    NothingToClaim: "Không có quỹ nào để nhận.",
    NotOwner: "Chỉ chủ sở hữu chiến dịch mới có thể thực hiện việc này.",
    NotAttester: "Chỉ người xác minh mới có thể thực hiện việc này.",
    InvalidCid: "CID hình ảnh không hợp lệ.",
    InvalidTitle: "Tiêu đề không hợp lệ.",
    rejected: "Đã hủy ký.",
    generic: "Giao dịch thất bại. Thử lại.",
  } as Record<string, string>,
};
